export type DisclaimerContext = 
  | 'EARNINGS_PROJECTION'
  | 'SOLAR_SAVINGS_ESTIMATE'  
  | 'FUNDING_QUALIFICATION'
  | 'AI_AGENT_OUTPUT'
  | 'TOKEN_REWARD_DISPLAY'
  | 'INVESTMENT_ADJACENT_LANGUAGE';

export const DisclaimerEngine = {
  getDisclaimer(context: DisclaimerContext): string {
    switch(context) {
      case 'EARNINGS_PROJECTION':
        return "NVK GLOBAL DISCLOSURE: Projected earnings are estimates based on historical pipeline velocity and are not guaranteed. Actual revenue depends on market conditions, lead quality, and sales execution. This is not a promise of future income.";
      case 'SOLAR_SAVINGS_ESTIMATE':
        return "NVK SOLAR DIRECTIVE: Savings projections are algorithmically estimated using local utility rates and historical usage. Due to weather anomalies, shading gradients, and grid tariffs, exact savings vary. This document does not constitute a legally binding guarantee of utility offset.";
      case 'FUNDING_QUALIFICATION':
        return "NVK FUNDING FORGE: Qualification scores are preliminary internal metrics generated by AI models simulating underwriter behavior. Only formal applications submitted to credentialed financial institutions will result in binding term sheets.";
      case 'AI_AGENT_OUTPUT':
        return "NVK SENTINEL SYSTEM: This output was synthesized by an AI Agent (NVK Nexus Cortex). While calibrated for high-fidelity business operations, you must independently verify critical data before executing enterprise-grade decisions or legal maneuvers.";
      case 'TOKEN_REWARD_DISPLAY':
        return "NVK XP PROTOCOL: XP and tokens represent internal organizational standing within the NVK ecosystem and currently hold no fractionalized fiat value. They are not investment instruments.";
      case 'INVESTMENT_ADJACENT_LANGUAGE':
        return "NVK GLOBAL COMPLIANCE: Information provided is for educational and strategic modeling purposes only. It does not constitute financial, legal, or investment advice.";
      default:
        return "NVK PROPRIETARY CONFIDENTIAL: Internal enterprise data payload. Treat with maximum operational security.";
    }
  },

  appendDisclaimer(content: string, context: DisclaimerContext): string {
    return `${content}\n\n---\n*${this.getDisclaimer(context)}*`;
  }
};
