export type DisclaimerContext = 
  | 'EARNINGS_PROJECTION'
  | 'SOLAR_SAVINGS_ESTIMATE'
  | 'FUNDING_QUALIFICATION'
  | 'AI_AGENT_OUTPUT'
  | 'TOKEN_REWARD_DISPLAY';

const DISCLAIMERS: Record<DisclaimerContext, string> = {
  EARNINGS_PROJECTION: "Results vary based on market conditions, lead quality, geographic location, individual effort, and business experience. NVK OS does not guarantee any specific income outcome. Past performance is not indicative of future results.",
  SOLAR_SAVINGS_ESTIMATE: "Solar savings projections are estimates only. Actual savings depend on roof orientation, local utility rates, geographic sun exposure, regulatory incentives, and physical site conditions. Requires professional on-site assessment.",
  FUNDING_QUALIFICATION: "Funding pre-qualification is indicative only and does not constitute a loan offer. Final approval is subject to certified commercial underwriting by licensed partner lenders.",
  AI_AGENT_OUTPUT: "This analysis was generated by an AI system and may contain errors or omissions. All recommendations should be reviewed by a qualified professional before implementation.",
  TOKEN_REWARD_DISPLAY: "Rewards and activity points are utility credits within the NVK OS platform. They do not constitute securities, investment instruments, or vehicles for capital appreciation."
};

export function getDisclaimer(context: DisclaimerContext): string {
  return DISCLAIMERS[context];
}

export function getApplicableDisclaimers(content: string): DisclaimerContext[] {
  const contexts: DisclaimerContext[] = [];
  if (/earn|income|commission|revenue|profit/i.test(content)) contexts.push('EARNINGS_PROJECTION');
  if (/solar|savings|kwh|utility/i.test(content)) contexts.push('SOLAR_SAVINGS_ESTIMATE');
  if (/funding|loan|capital|underwriting/i.test(content)) contexts.push('FUNDING_QUALIFICATION');
  contexts.push('AI_AGENT_OUTPUT');
  return contexts;
}
